### ISSUE TITLE
htc vive twitch acount suspended when connect 

### ISSUE THREAD

**Issue by DJBeatTheBasDog** [Hotrian/OpenVRTwitchChat#15]
i have problem it saying my twitch channel has been suspended but hasn't talk to twitch they say it not suspend so something not work well with the htc vive?

**Comment by Hotrian** [comment]
What channel are you trying to connect to? Also, what version are you using to connect? I see that [you commented on Reddit](https://www.reddit.com/r/Vive/comments/4tfr4j/my_twitch_chat_overlay_program_now_experimentally/d5hg9xa) too but I'll comment here in case other users have this error as well.

**Comment by Hotrian** [comment]
I believe I fixed this in 355ce90fc90c2898cd9051681c775d548aeb68a0, just waiting for you to confirm :).

**Comment by Hotrian** [comment]
DJBeatTheBasDog confirmed this was fixed [on Reddit](https://www.reddit.com/r/Vive/comments/4tfr4j/my_twitch_chat_overlay_program_now_experimentally/d5il7iv) a few hours ago, but I forgot to close it until now.
