### ISSUE TITLE
Question about License

### ISSUE THREAD

**Issue by Genteure** [Hotrian/OpenVRTwitchChat#25]
May I use and modify this project, and which license should I follow?
I want to make a tool basically same as OpenVRTwtichChat but for a non-english platform.

**Comment by Hotrian** [comment]
OVRTC itself has not yet been released under any specific license (meaning I retain all rights, excluding the bits of code which are already licensed (parts of the Save/Load and TwitchIRC code), and the sound effects which are also under their own license).

Are you planning to use OVRTC commercially, or non-commercially?

**Comment by Genteure** [comment]
Non-commercially. The platform I want to work on have just a few VR streamer and I only know three. It's more like a hobby project.
The streaming platform is [bilibili(Chinese)](https://live.bilibili.com), and there is an opensource desktop stream chat tool [bililive_dm](https://github.com/copyliu/bililive_dm/) I did some contribution in the past.

> OVRTC itself has not yet been released under any specific license

That's why I'm asking :smile:

**Comment by Hotrian** [comment]
I offer you the following agreement in lieu of a proper license:

>I grant _you_ explicit perpetual permission to utilize OVRTC (whether in source or binary form) for _non-commercial_ purposes. You may not sell OVRTC or any of its derivatives, but you may give it away freely (either as source or binary), and use personally (either privately or publicly). 
>
>You are free to modify OVRTC in any way that you see fit. I cannot be held liable for any damages that result from your modifications, distribution, or usage of OVRTC or its derivatives.
>
>I retain the right to revoke this permission if you attempt to violate this agreement, regardless of success. The same rules apply to anyone who obtains a copy of OVRTC or its derivatives from you, and anyone who receives a copy from them, etc.
>
>Individuals utilizing OVRTC or its derivatives in a live stream is not considered to be commercial usage for the purposes of this agreement. Businesses may not enter into this agreement. 

I would be happy to extend this non-commercial agreement to anyone who is interested: simply comment here or email me directly and I will confirm permission is granted.

If anyone wishes to discuss educational or commercial licensing, I would be happy to discuss this via email.

**Comment by Genteure** [comment]
Thanks!
