### ISSUE TITLE
Running multiple apps at once may cause performance issues.

### ISSUE THREAD

**Issue by joseph-allen** [Hotrian/OpenVRTwitchChat#31]
I cannot launch other games while this program is running.

I get an error from occulus "Running multiple apps at once may cause performance issues. Please close the current app before opening another app."

**Comment by Hotrian** [comment]
OVRTC is a SteamVR app. Are you running it along side a SteamVR title? Some Steam games will utilize the Oculus SDK and boot up through Oculus Home, preventing OVRTC from rendering. 

Either way, this is probably something I can’t change and Oculus is just preventing apps like OVRTC from functioning properly. There might be an option in Oculus Home to fix this, but it wouldn’t be something OVRTC can change, or anything I could fix. Oculus needs to fix this. 

Edit: Yeah, looks like Oculus is trying to get rid of side-loaded apps and the API for them is deprecated. This is an Oculus issue, and not something I can fix, and it looks like they consider it a feature, so they aren't going to fix it.

**Comment by joseph-allen** [comment]
no problem, big shame on Oculus :(
