### ISSUE TITLE
I Messed Up

### ISSUE THREAD

**Issue by DuffyFlumpling** [Hotrian/OpenVRTwitchChat#33]
I launched the Overlay thing in Monitor 2 which is my VR Set and everytime I open it I get a red screen and can't do anything. Is there any way I can make it open in Monitor 1 which is my laptop screen? Please help me.

**Comment by Hotrian** [comment]
Could you attach your output_log.txt?

You could try launching OVRTC with the launch flag `-show-screen-selector` which is Unity's way of selecting which monitor to use.

**Comment by DuffyFlumpling** [comment]
Where is that? What is that? I am so confused. It's been 4 hours.

**Comment by Hotrian** [comment]
What has been 4 hours? You only posted this issue 2 hours ago and I responded right away.

The output_log.txt file can be found inside the OpenVRTwitchChat_Data folder. OVRTC is no longer under active development and when Twitch updates their API to version 3 it will likely no longer work as #32 states.

**Comment by DuffyFlumpling** [comment]
No I mean I was working on trying to fix it for 4 hours and then did an issue haha.
I can't find the file. This sounds stupid but it's literally nonexistent.

**Comment by Hotrian** [comment]
Hmm maybe try deleting and redownloading OVRTC. I don't think there's anything that should cause a red screen in OVRTC. Without the output_log.txt I can't tell you what's going on. You could try using the `-show-screen-selector` launch flag if you think putting it on your other monitor would help.

Because it's built on Unity, there are registry keys being created that will persist even through a delete/redownload, and it's possible those registry keys are causing issues, but without the output_log.txt I have nothing to go on.

**Comment by DuffyFlumpling** [comment]
Thank you. I'll try to figure it out.

So I did the launch flag thing and I still get a red screen from my Vive but I see the OVRTC program thing. Even when I run VR Chat, I still get the red screen but see the game on my laptop monitor.

I found this 
VR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Driver_HmdDisplayMirrored: "HMD detected over USB, but Monitor may be mirrored instead of extended (212)"!
 
(Filename:  Line: 1027)

**Comment by Hotrian** [comment]
That's a SteamVR error, so this is likely a SteamVR problem? You have a red screen in the Vive itself? OVRTC shouldn't be able to cause that.

**Comment by DuffyFlumpling** [comment]
I really don't know how to explain it. I think that when I told the program to launch OVRTC in Monitor 2 (Vive Headset) It messed it up to where I get a red headset window whenever OVRTC launches. I am playing on a laptop with only one monitor. It counts my Vive as a monitor. I don't know how to make the OVRTC relaunch in Monitor 1. I think I really did goof.

**Comment by Hotrian** [comment]
OVRTC shouldn't need to launch on a specific monitor, and your HMD should not display as a monitor to the system. There's a setting in SteamVR to put the HMD into Direct Mode and I think that's what you need.

**Comment by DuffyFlumpling** [comment]
It never works when I click Direct Mode.

**Comment by Hotrian** [comment]
Sounds more and more like a SteamVR issue. If you can select OVRTC with Alt+Tab, you can do `Windows Key + Shift + Left Arrow` to move the window to the other monitor. Normally when the compositor loses focus you can just alt+tab back to it to fix it. When SteamVR is not in direct mode, it is drawing a compositor window to the HMD's display, and if the compositor loses focus SteamVR doesn't work properly (red screen).

OVRTC itself cannot cause this issue. What's happening is you have another window on the HMD's display (possibly the OVRTC window) and the compositor window is not gaining focus.

Your best solution is to put the HMD back into Direct Mode. Try turning off and on Direct Mode and see if that works?

**Comment by Hotrian** [comment]
I am closing this one for being stale. If this is still happening please reopen this issue.
