### ISSUE TITLE
Stops working when shortly leaving Steam VR

### ISSUE THREAD

**Issue by steelmonkey** [Hotrian/OpenVRTwitchChat#40]
Im ruining windows mix realty so when shortly suspended steam vr use my Windows VR hub accesses my desktop and then go back to steam VR twitch chat is no longer visible forcing me to fully close VR to restart the program. Its not even fully closing steam vr just suspending it idk why it dose that.

**Comment by Hotrian** [comment]
Hmm, that might be an issue with SteamVR. Do other overlay applications do the same? I don’t have a WMR headset so I wouldn’t be able to debug this one unfortunately.

**Comment by Hotrian** [comment]
I am closing this one for being stale. If this is still happening please reopen this issue.
