### ISSUE TITLE
No longer displays chat while in VR + Twitch API Changes

### ISSUE THREAD

**Issue by KingGold171** [Hotrian/OpenVRTwitchChat#41]
Up untill recently everything was working fine.
Not sure if its related to a SteamVR update or not.

I have tried OVRDrop on stream but had no luck getting the window to display or connect to chat, so i guess the issues are across the board. (Since been refunded)

I like the concept of OVRDrop, but the simplicity of OVRTC and only being twich chat on a controller is much nicer to look at then a whole browser window,

**Twitch API**
Since i work with Twitch API regually for other projects it was easy to update from Kracken to the new Helix API so connecting to chat displaying is simple.
Error on page (https://api.twitch.tv/kraken/streams/kinggold171): 410 Gone
Error on page (https://api.twitch.tv/kraken/channels/kinggold171/follows?limit=100): 410 Gone
These errors are fixed. along with other Twitch related ones.

Only thing left to work out is why you can't see the chat overlay in VR.

Code for fixing all Twitch API changes can soon be released as a Pull Request.

**Comment by Hotrian** [comment]
If you are having issues with overlays across the board, this is likely a SteamVR issue. 

OVRdrop is designed to copy a window into VR, so it doesn’t connect to any chat — most people using OVRdrop for this are using Twitch’s popout chat and cloning that. As for displaying in VR, overlays are actually drawn by SteamVR. Which headset are you using?

**Comment by KingGold171** [comment]
HTC Vive

I have tried Twitch Chat popout window.

It does show on OVRDrop screen, just never In VR (World, Screen or controller)

**Comment by Hotrian** [comment]
Could you attach the output_log.txt from inside the OVRdrop_Data folder?

Could you also post screenshots of the OVRdrop window with the Additional Settings menu open?

**Comment by KingGold171** [comment]
https://www.screencast.com/t/X0BAVlCxiY
[output_log.txt](https://github.com/Hotrian/OpenVRTwitchChat/files/4461285/output_log.txt)

SteamVR 1.10.32

**Comment by Hotrian** [comment]
Thanks! Unfortunately nothing immediately stands out as being an issue.

Can you see any overlays in VR? Can you see the SteamVR dashboard overlays? Can you see SteamVR's notifications?

The fact you seem to have an issue with both OVRTC and OVRdrop makes me think SteamVR itself is failing to composite overlays. A setting may have been turned off, or a file or configuration may have become corrupted in SteamVR. Googling around I found one person who couldn't get any overlays working until they completely reinstalled Steam itself, which may point to a configuration file.

**Comment by KingGold171** [comment]
It was working before a SteamVR update.

Will test other Steam related overlays and if that fail  i shall go down route of reinstalling Steam and SteamVR.

From what i have seen SteamVR is not as easy to rollback to previous version.

Will post results in due course.

**Comment by KingGold171** [comment]
Reinstalled Steam and SteamVR
Can see steam chat messages popup and friends playing games.
Normal SteamVR overlays/menus are working as expected.

OVRDrop and OVRTC still fail to display
Im still fixed on possibility of SteamVR Update causing breaking changes.

**Comment by KingGold171** [comment]
[output_log.txt](https://github.com/Hotrian/OpenVRTwitchChat/files/4463812/output_log.txt)
after reinstall of steam and steamvr.  From ovrdrop

**Comment by Hotrian** [comment]
OVRdrop is still working for me on 1.10.32 and unfortunately that log only contains informational output and no actual errors. It normally would contain actual errors, but none seem to be being thrown by OVRdrop. I would guess this is a SteamVR issue on your PC, and there’s nothing directly I can do to fix it.

**Comment by KingGold171** [comment]
Reinstalled Everything...

- Windows 10
- Steam
- SteamVR

Yet still doesn't work. So i've just refunded on Steam.
Sorry but untill i know whats going on, not worth owning.

**Comment by Hotrian** [comment]
I am closing this one for being stale. If this is still happening please reopen this issue.
