### ISSUE TITLE
OpenVR System not found

### ISSUE THREAD

**Issue by BaKarl** [Hotrian/OpenVRTwitchChat#42]
Hi, 
If i want to connect my Twitch Acc i just get the message 
System: OpenVR System not found.
Disconnected

 [https://ibb.co/BG451mw](url)
want Im doing wrong?

**Comment by Hotrian** [comment]
I assume you have SteamVR installed and running? This error means OVRTC was not able to find the OpenVR/SteamVR system, which can also happen if SteamVR is throwing some error such as Headset not found.

**Comment by Hotrian** [comment]
I am closing this one for being stale. If this is still happening please reopen this issue.
